spring.application.name=NeuroForge-Nexus

server.port=8082

# H2 Database configuration (Default for local running)
spring.datasource.url=jdbc:h2:mem:neuroforge_nexus;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# MySQL configuration (Optional, comment H2 above and uncomment this to use MySQL)
# spring.datasource.url=jdbc:mysql://localhost:3306/neuroforge_nexus
# spring.datasource.username=root
# spring.datasource.password=Dhanu@2007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console